### PR TITLE
add leaflet.fullscreen

### LINKED ISSUE #187: Leaflet fullscreen
Hello,

It would be nice to be able to use `enablefullscreen` with Leaflet.
There is a nice plugin that does that: https://github.com/brunob/leaflet.fullscreen

(Originally reported here: https://github.com/SemanticMediaWiki/SemanticMaps/issues/86)

### PR DESCRIPTION
**Pull request by PeterTheOne**
fix #187

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Awesome!

**Comment by PeterTheOne** [comment]
@kghbln I renamed `maps-googlemaps3-par-enable-fullscreen` in `en.json` and `qqq.json`, should I have renamed them in all the other languages also?

**Comment by Nikerabbit** [comment]
I have renamed fullscreen and kml messages in translatewiki.net. No further action for them is needed.

**Comment by PeterTheOne** [comment]
@Nikerabbit so https://github.com/JeroenDeDauw/Maps/pull/201 is not needed?

**Comment by Nikerabbit** [comment]
It's not necessary. But, it does not hurt either and makes sure these files are updated now and not some time later during exports.

**Pull request merged**
