### PR TITLE
Fixed OpenLayers invalid style.css path with ResourceLoader enabled

### PR DESCRIPTION
**Pull request by Fannon**
@JeroenDeDauw 
I hope this fixes it.

### CODE REVIEW

**Comment by Fannon** [comment]
The CI tests run out of time.

**Comment by JeroenDeDauw** [comment]
Thanks a lot for submitting this PR. Just ignore the CI, one of them passed and the other ones failed due to Travis being flaky. Besides, there are no tests for what you touched anyway.

**Comment by Fannon** [comment]
Yes, I thought so too.

**Comment by JeroenDeDauw** [comment]
Why did you close this?

**Comment by Fannon** [comment]
Sorry, I thought this pull request was already complete.

**Comment by JeroenDeDauw** [comment]
Ok, merged now. Thanks again!

**Comment by Fannon** [comment]
Your're welcome!

**Pull request merged**
