### PR TITLE
Make table more compact

### PR DESCRIPTION
**Pull request by kghbln**

### CODE REVIEW

**Comment by kghbln** [comment]
@JeroenDeDauw A squash and merge will be cool.

**Comment by JeroenDeDauw** [comment]
Why this change?

**Comment by kghbln** [comment]
It saves one ore two centimeters in width which is good on mobile devices I guess.

**Comment by JeroenDeDauw** [comment]
I like the SMW newline, though to be honest I think the table was easier to understand without the other change

**Comment by kghbln** [comment]
Hmm, I guess this is just a matter of habit.

**Pull request merged**
