### PR TITLE
fixes #401; resource loading broken when maps not located directory named 'extensions'

### LINKED ISSUE #401: resource loading broken when maps not located directory named "extensions"
### Setup

- Maps version: 5.1.0
- MW version: 1.27.4
- PHP version:  5.6
- SMW version (if applicable): 2.5.5

### Issue
My extensions are not located "below" but rather "next to" the mediawiki directory. e.g.:

```
_extensions
_images
mediawiki
_skins
```
Furthermore, the directory containing the extensions is not named "extensions". 

Integration is done via symlink located in the mediawiki directory
```
mediawiki/extensions -> ../_extensions
```
and also by setting `$wgExtensionDirectory`. Works so far perfectly.

Unfortunately, with maps resource loading fails in
```
Maps.resources.php
includes/services/GoogleMaps3/GoogleMaps3.php
includes/services/Leaflet/Leaflet.php
includes/services/OpenLayers/OpenLayers.php
```
Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

move Maps to a directory other than "extensions". ;)

### PR DESCRIPTION
**Pull request by oetterer**
changed path detection in problematic resource files.

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Thanks a lot @oetterer! Did you test this against the normal MediaWiki-style setup as well?

**Comment by oetterer** [comment]
My tests "at home" are limited in the way that I don't have php 7 at hand. So I tested Maps 5.0.2. Resource loading did not change between that and master, though.

My tests in a regular environment did not have SMW installed, so I used the examples from
* https://www.semantic-mediawiki.org/wiki/Maps_examples/Google_Maps_marker_clustering
* https://www.semantic-mediawiki.org/wiki/Maps_examples/Leaflet_marker_clustering
* https://www.semantic-mediawiki.org/wiki/Maps_examples/OpenLayers_searchmarkers

When I open the test wiki pages with `debug=true` and watch the network traffic, there are only status 200 requests (and, of course, the maps show as expected).

Do you have some more tests in mind, I could do?

**Comment by JeroenDeDauw** [comment]
Where the tests you described done with the "normal" setup (an extensions/ directory inside of the MW one)?

**Comment by oetterer** [comment]
Yeah. That's what I meant with "regular environment". `mediawiki/extensions/Maps`.

**Comment by JeroenDeDauw** [comment]
Thanks for the patch and providing the extra info!

**Comment by JeroenDeDauw** [comment]
https://github.com/JeroenDeDauw/Maps/blob/master/RELEASE-NOTES.md#maps-520

**Pull request merged**
