### PR TITLE
Merged SM messages into the main messages file

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Part of #233

@Nikerabbit am I doing it right?

### CODE REVIEW

**Comment by Nikerabbit** [comment]
Looks right.

**Comment by JeroenDeDauw** [comment]
Thanks for the review!

**Comment by JeroenDeDauw** [comment]
Should I remove  	`SemanticMaps/i18n` myself or will the twn stuff do that?

**Comment by Nikerabbit** [comment]
Those files are not part of any automated translatewiki.net process, so you should do it.

**Comment by JeroenDeDauw** [comment]
Ok https://github.com/JeroenDeDauw/Maps/pull/267

I hope that the translations already made do not get lost this way. Or are they, and if so, is there a way to prevent that?

**Comment by Nikerabbit** [comment]
I will do an export tomorrow and they should all be added to the existing files. Let's see then.

**Comment by Nikerabbit** [comment]
Some files did not update, I noticed GitHub projects were using the default 35% export threshold instead of no threshold as is used for other MediaWiki extensions. I fixed this, but then I could not push an update. Have you changed something?

```
cd /resources/nike/mwgithub/JeroenDeDauw/Maps; git add .; if git commit -m 'Localisation updates from https://translatewiki.net.'; then git push origin 'master'; fi
[Fri Oct 14 11:33:13 2016] [hphp] [4370:7f2176a8d400:0:000001] [] 
Fatal error: Uncaught exception 'Symfony\Component\Process\Exception\ProcessFailedException' with message 'The command "cd /resources/nike/mwgithub/JeroenDeDauw/Maps; git add .; if git commit -m 'Localisation updates from https://translatewiki.net.'; then git push origin 'master'; fi" failed.

Exit Code: 1(General error)

Working directory: /resources/nike

Output:
================
[master 651b7d3] Localisation updates from https://translatewiki.net.
 85 files changed, 381 insertions(+), 308 deletions(-)
 create mode 100644 i18n/ckb.json
 create mode 100644 i18n/cy.json
 create mode 100644 i18n/inh.json
 create mode 100644 i18n/lki.json
 create mode 100644 i18n/tcy.json


Error Output:
================
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "continuous-integration/travis-ci" is expected. At least one approved review is required.
To git@github.com:JeroenDeDauw/Maps.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:JeroenDeDauw/Maps.git'
' in /resources/nike/translatewiki/repong/vendor/symfony/process/Process.php:232
Stack trace:
#0 /resources/nike/translatewiki/repong/repong.php(136): Symfony\Component\Process\Process->mustRun()
#1 /resources/nike/translatewiki/repong/repong.php(191): RepoNg->commit()
#2 {main}
```

**Comment by JeroenDeDauw** [comment]
> using the default 35% export threshold

I don't know what that means. Is this about some TWN threshold?

> I fixed this, but then I could not push an update. Have you changed something?

Bah. Yeah, I turned on branch protection for `master`. I decreased it now, so you should no longer have the issue. I forgot about TWN when configuring that.

**Comment by JeroenDeDauw** [comment]
Meh... I'm not so happy with this. I turned on the branch protection since someone accidentally deleted some code on master (via direct push). It'd be nice to prevent direct pushes in such a way TWN does not break.

**Comment by Nikerabbit** [comment]
Unless it has whitelist feature, I don't see any easy way.

**Pull request merged**
