### PR TITLE
Add missing i18n vars

### PR DESCRIPTION
**Pull request by paladox**
This is needed to load the i18n if you use LocalisationCache ie rebuildLocalisationCache.php.

### CODE REVIEW

**Comment by paladox** [comment]
This fixes the issue for me locally.

**Comment by JeroenDeDauw** [comment]
Thanks!

**Comment by JeroenDeDauw** [comment]
https://github.com/JeroenDeDauw/Maps/commit/c4270a989cf0f7853291ba35d1343ce0f997efad#diff-89f3cba2993eebd391f32c27f3772d7b

**Comment by paladox** [comment]
Thanks!

**Pull request merged**
