### PR TITLE
Removed SMW compat upper bound from composer.json

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Since apparently it prevents installation together with SMW dev-master

### CODE REVIEW

**Comment by kghbln** [comment]
Pls give me a ping as soon as this got merged so I can add it to sandbox again.

**Comment by JeroenDeDauw** [comment]
@kghbln

**Comment by kghbln** [comment]
@JeroenDeDauw There is still somthing wrong:

  - Updating mediawiki/maps (3.8.2 => 3.8.x-dev a5a1d77)
    Checking out a5a1d771f56c43f463c3503f89454f77d4d48477

At least it does no longer revert SMW to 2.4.1

**Comment by JeroenDeDauw** [comment]
Is it fixed now? I made this change https://github.com/JeroenDeDauw/Maps/commit/8dcca6d71ce0a356d33a2c94a4f50bd2621e4878

**Comment by kghbln** [comment]
> Is it fixed now?

Affirmative. It seems that this "conflict" parameter still needs some work.

**Pull request merged**
