### PR TITLE
add MapQuest Layer

### PR DESCRIPTION
**Pull request by krabina**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Belongs together with #112

I'm not able to test this. Would be nice to get confirmation from another user that this works as expected

**Comment by krabina** [comment]
a working example can be seen here: http://bacid.kdz.eu/

**Comment by JeroenDeDauw** [comment]
Thanks!

**Comment by JeroenDeDauw** [comment]
Can you also submit an update to the release notes?

**Pull request merged**
