### PR TITLE
Merged in Semantic Maps extension

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
See https://github.com/JeroenDeDauw/Maps/issues/233

### CODE REVIEW

**Comment by kghbln** [comment]
Refs https://github.com/JeroenDeDauw/Maps/issues/233

**Comment by JeroenDeDauw** [comment]
This now appears to work... though it's hard to tell without an actual wiki :) Can someone try it out and see if their wiki explodes or not, and if not, if the "Semantic Maps" features are showing up?

**Comment by JeroenDeDauw** [comment]
@kghbln getting this tested and merged actually blocks me adding this "disable maps" setting

**Comment by kghbln** [comment]
Wow, this was a monster commit.

**Comment by JeroenDeDauw** [comment]
* Monster PR :) It's 1,390 commits

**Pull request merged**
