### PR TITLE
Switching to protocol relative URLs

### PR DESCRIPTION
**Pull request by kghbln**
Fixing issue https://github.com/JeroenDeDauw/Maps/issues/90 by changing to protocol relative URLs

### CODE REVIEW

**Comment by kghbln** [comment]
@JeroenDeDauw I am being bold here, but I thing this should help the cause and eradicate the transgressions. Keeping fingers crossed.

**Comment by JeroenDeDauw** [comment]
Did you test that the relevant images are still displayed correctly after these changes?

**Comment by kghbln** [comment]
@JeroenDeDauw Did so now. Affirmative, it works perfect and even solves other issues like on [this page](https://semantic-mediawiki.org/wiki/Maps_examples/Google_Maps_map_with_one_marker_having_an_inline_label). Ready to merge I guess. :)

**Comment by JeroenDeDauw** [comment]
\o/ thanks again!

**Comment by JeroenDeDauw** [comment]
Rel notes have been updated

**Pull request merged**
