### PR TITLE
Added compat for old egGoogleJsApiKey setting

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Fixes https://github.com/JeroenDeDauw/Maps/issues/250

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
@kghbln are we actually dealing with the same API key here though? Or will people still need to update the value of the setting if they have it from Maps 2.x?

**Comment by kghbln** [comment]
Well I am assuming here that Google does not require to change an existing key. This would be bull... imho so I did not even consider this as an potential issue. To tell the truth: I do not know how the keys looked like back then and how they look like now.

**Comment by JeroenDeDauw** [comment]
Well... that's kinda relevant :)

**Comment by kghbln** [comment]
Well it depends if the key was generated for v2 or v3. If it was generated for v2 one [needs to get a new key](https://developers.google.com/maps/documentation/javascript/v2tov3#newkey). However I believe that the v2 no longer works and people using a key via the precursor setting are already using a v3 key. So yes it should be the same key.

**Pull request merged**
