### PR TITLE
Add missing cluster marker images

### PR DESCRIPTION
**Pull request by PeterTheOne**
Fix: #138
Alternative to: #139

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Great, thanks!

I take it you tested this?

**Comment by kghbln** [comment]
Works, see [sandbox](http://sandbox.semantic-mediawiki.org/wiki/Google_Maps_marker_clustering). Thanks for the change.

**Comment by PeterTheOne** [comment]
Yes, I tested it.

**Comment by PeterTheOne** [comment]
Btw. it was fixed upstream https://github.com/googlemaps/js-marker-clusterer/commit/cb2ead36604b2a244f63ae09b48e77452eceb901  and I'm trying to get the documentation fixed https://github.com/googlemaps/js-marker-clusterer/pull/75 .

Also feel free to upvote http://stackoverflow.com/a/37499989/782920 and http://stackoverflow.com/a/37500068/782920 .

**Pull request merged**
