### PR TITLE
Update to leaflet version 1.0.0(-rc2)

### PR DESCRIPTION
**Pull request by PeterTheOne**
I think we shouldn't merge this yet, let's wait for 1.0.0. But we can use this PR for testing.

Also see: #141

### CODE REVIEW

**Comment by kghbln** [comment]
Getting close to -rc2 https://github.com/Leaflet/Leaflet/issues/4732

**Comment by PeterTheOne** [comment]
This branch is now on [leaflet 1.0.0-rc2](http://leafletjs.com/2016/07/16/leaflet-1.0-rc2.html). I did have a quick look if it works and it did but I haven't tested comprehensively.

**Comment by PeterTheOne** [comment]
I'm ok with merging this before 1.0.0 is out, if anyone wants to. But we could also wait for the last bugs to be fixed.

**Comment by kghbln** [comment]
> I'm ok with merging this before 1.0.0 is out

Me too since it would allow testing on sandbox before the next release of Maps gets out to the world. @JeroenDeDauw Thoughts or action? :)

**Pull request merged**
