### PR TITLE
Removed broken layers functionality

### LINKED ISSUE #168: Disable or remove Layer: functionality
Regarding the functionality tied to the Layer: namespace introduced in Maps 3.0 https://github.com/JeroenDeDauw/Maps/blob/master/RELEASE-NOTES.md#new-features

This code was added in a dubious state and has received no maintenance since. I am not aware of anyone using this functionality, or documentation of it. I would thus not be surprised if it is currently broken.

Some serious issues with the functionality have been brought to my attention. These issues require follow up. If no one presents a good argument for keeping this functionality, I'm inclined to remove it.

If anyone is aware of users or documentation of this functionality, or is otherwise awesome of its status, please point this out.

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Fixes #168

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Huh, nothing blew up, even without me running the tests? That just makes me think stuff did blow up but the tests did not catch it :)

**Comment by JeroenDeDauw** [comment]
This was about 1/3rd of the PHP code in Maps...

**Comment by JeroenDeDauw** [comment]
@kghbln if the sandbox totally breaks now, you know who to throw the tomatoes at

**Comment by PeterTheOne** [comment]
Indeed a lot of code.. O.o

**Comment by kghbln** [comment]
> if the sandbox totally breaks now, you know who to throw the tomatoes at

Just to make sure. Should these tomatoes be rotten? :D

**Comment by kghbln** [comment]
I does not. Just updated to latest master and at least we do not have fatals. Error log does not seem to collect issue information either.

**Comment by JeroenDeDauw** [comment]
Thanks @kghbln

**Pull request merged**
