### PR TITLE
[DNM] Use latest version of Leaflet

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Not getting this to work properly...
Been trying for an hour to get the resources loaded, but my wiki
is not allowing access to files in vendor/ it seems. Might be that
it is configured badly. I don't want to spend more time on MW shit,
though would be awesome if someone figures out what the issue is.

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
@mwjames you any idea how to make this work?

@PeterTheOne FYI

**Comment by kghbln** [comment]
@JeroenDeDauw What is the difference to #326 ?

**Comment by JeroenDeDauw** [comment]
With this change the leaflet code is not included in the Maps repo but pulled in via Composer. Just going to close this, someone can have another go if they want.

**Comment by kghbln** [comment]
Ah, this would indeed have been nice. :|

**Comment by PeterTheOne** [comment]
Great idea, but was the vendor path something that is reachable for the web browser?

**Comment by JeroenDeDauw** [comment]
I suppose not, looking at what I wrote. I don't really recall though

**Pull request closed without merging**
