### PR TITLE
Update jquery.miniColors.js

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Hey. Thanks for your patch. This looks like a breaking change to me. So someone needs to verify the editor still works with the latest version of this library. ping @netbrain

**Comment by JeroenDeDauw** [comment]
@kghbln any idea who I can ask for verification? I don't know who is using the editor...

**Comment by kghbln** [comment]
@JeroenDeDauw Is this about [Special:MapEditor](https://semantic-mediawiki.org/wiki/Special:MapEditor?)

**Comment by JeroenDeDauw** [comment]
Yeah

**Pull request closed without merging**
