### PR TITLE
Use IDatabase instead of DatabaseBase

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Fixes https://github.com/JeroenDeDauw/Maps/issues/557

### CODE REVIEW

**Comment by mwjames** [comment]
The master fails due to `MaintainableDBConnRef`.

```
1) Maps\Tests\Semantic\ValueDescriptions\AreaDescriptionTest::testGetSQLCondition
TypeError: Argument 3 passed to Maps\SemanticMW\ValueDescriptions\AreaDescription::getSQLCondition() must be an instance of Wikimedia\Rdbms\Database, instance of Wikimedia\Rdbms\MaintainableDBConnRef given, called in /home/travis/build/JeroenDeDauw/phase3/extensions/Maps/tests/Integration/Semantic/ValueDescriptions/AreaDescriptionTest.php on line 52
/home/travis/build/JeroenDeDauw/phase3/extensions/Maps/src/SemanticMW/ValueDescriptions/AreaDescription.php:86
/home/travis/build/JeroenDeDauw/phase3/extensions/Maps/tests/Integration/Semantic/ValueDescriptions/AreaDescriptionTest.php:52
/home/travis/build/JeroenDeDauw/phase3/maintenance/doMaintenance.php:99
2) Maps\Tests\Semantic\ValueDescriptions\AreaDescriptionTest::testWhenComparatorIsNotSupported_getSQLConditionReturnsFalse
TypeError: Argument 3 passed to Maps\SemanticMW\ValueDescriptions\AreaDescription::getSQLCondition() must be an instance of Wikimedia\Rdbms\Database, instance of Wikimedia\Rdbms\MaintainableDBConnRef given, called in /home/travis/build/JeroenDeDauw/phase3/extensions/Maps/tests/Integration/Semantic/ValueDescriptions/AreaDescriptionTest.php on line 64
/home/travis/build/JeroenDeDauw/phase3/extensions/Maps/src/SemanticMW/ValueDescriptions/AreaDescription.php:86
/home/travis/build/JeroenDeDauw/phase3/extensions/Maps/tests/Integration/Semantic/ValueDescriptions/AreaDescriptionTest.php:64
/home/travis/build/JeroenDeDauw/phase3/maintenance/doMaintenance.php:99
```

`class MaintainableDBConnRef extends DBConnRef` and 

`class DBConnRef implements \Wikimedia\Rdbms\IDatabase`


[0] https://github.com/wikimedia/mediawiki/blob/b5e255e914f0fe70890f8ac61d9d19476699873e/includes/libs/rdbms/database/MaintainableDBConnRef.php

**Comment by mwjames** [comment]
`AreaDescriptionTest` uses `wfGetDB( DB_MASTER )` which since [0] returns a `MaintainableDBConnRef`

[0] https://github.com/wikimedia/mediawiki/commit/9aeea7989766f2fec8920510ea8815aa403f9edb

**Comment by JeroenDeDauw** [comment]
You're quite welcome to make PRs @mwjames ;) Don't get me wrong, I do appreciate the comments.

**Comment by JeroenDeDauw** [comment]
Annoying that Store and ConnectionManager in SMW return `mixed`

**Comment by mwjames** [comment]
> Annoying that Store and ConnectionManager in SMW return `mixed`

I'm not sure what the failing test has to do with that. It returns
`mixed` because it can return an ElasticClient instance, a Database,
or even a SPARQL repository instance which is manged by the
`ConnectionManager`.

Only because of this we are able to invoke different providers [0]
without diluting the codebase with MW specific callers.

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/SQLStore/QueryEngine/DescriptionInterpreters/SomePropertyInterpreter.php#L290-L300

**Comment by JeroenDeDauw** [comment]
Well I spend 5 minutes trying to figure out what SMW is actually passing to the code I modified here and gave up on it.

**Pull request merged**
